#Application Configuration
server:
  port: 8081

spring:
  application:
    name: costumer-service
  datasource:
    url: jdbc:mysql://localhost:3306/costumer-service
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Online Store"
appVersion: "1.0.0"
