#Application Configuration
server:
  port: 8082

spring:
  application:
    name: costumer-service
  datasource:
    url: jdbc:mysql://localhost:3306/costumer-service
    username: root
    password: komodor11
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Online Store"
appVersion: "1.0.0"
