#Application Configuration
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    username: root
    password: ${password}

  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Online Store"
appVersion: "1.0.0"